// Shadow git ledger — the high-resolution, canvas-owned file/artefact timeline.
// Design: docs/shadow-git-ledger.md. The trick is git's independent --git-dir / --work-tree: the SAME files
// are tracked by a SECOND repo whose database lives under `.canvas/`, so per-save commits never touch the
// human's `.git` (files shared, commits distinct — the "dotfiles bare repo" pattern). See doc §3.
//
// This module owns the commit mechanics, the per-root lock, and the per-root watch→settle→commit primitive
// (`watchRoot`). The engine (vite-fs-plugin.ts) orchestrates which roots exist and runs boot-reconcile.
//
// Attribution (doc §6, revised): the watcher floor is author-blind — it only ever sees a PATH, never a
// writer — so its settle-batch is the honest `external` floor. Rich attribution comes from the SESSION
// stdout: an Edit/Write tool call names both the session AND the exact file, so the engine commits JUST
// that path (`commitClaimed`), attributed. Turn-boundary attribution was abandoned: a turn spans many
// edits over minutes and a whole-tree `add -A` snapshot under concurrent agents attributes one agent's
// in-flight files to another. Path-scoped staging is what makes per-session commits truthful — A's commit
// holds A's file only. Bash/out-of-band writes (no path we can name) keep falling to the `external` floor.

import fs from "node:fs";
import path from "node:path";
import { execFile } from "node:child_process";
import { watch } from "chokidar";

// Honest floor attribution (doc §5/§6): the watcher cannot reliably tell WHICH session made an edit, so the
// floor labels `external`. Rich attribution (session id + turn message) is a later Stop-hook concern.
export const EXTERNAL_AUTHOR = "foolscap-external <external@foolscap.local>";

// Where a root's shadow database lives. Central under `.canvas/` so one board spans many worktrees and the
// history survives `git worktree remove` (doc §4). `gitRoot` is the primary root that owns `.canvas/`.
export function shadowGitDir(gitRoot, rootId = "repo") {
  return path.join(gitRoot, ".canvas", "roots", rootId, "git");
}

// The shadow repo's OWN excludes (doc §3, review M1) — a backstop independent of the human's `.gitignore`,
// so `add -A` can't swallow node_modules/dist/the shadow databases even if the human's ignore lacks them.
// Canvas content under `.canvas/` is NOT re-included here by negation: git cannot re-include a path once a
// parent dir is excluded by a higher-precedence in-tree `.gitignore` (and the human repo ignores `.canvas/`
// wholesale). So `.canvas/` content is force-added explicitly in commitRoot instead (whole tree minus the
// `.canvas/roots/` object stores) — robust regardless of ignore precedence (docs/canvas-home.md §3/§4).
const SHADOW_EXCLUDES = [
  "# generated by foolscap shadow-git — do not edit",
  "node_modules/",
  "dist/",
  "build/",
  ".vite/",
  ".cache/",
  "coverage/",
  ".git/",
  ".canvas/",
  "",
].join("\n");

// ── git invocation helpers ──────────────────────────────────────────────────────────────────────
function run(args, cwd) {
  return new Promise((resolve) => {
    execFile("git", args, { cwd, maxBuffer: 64 * 1024 * 1024 }, (err, stdout, stderr) => {
      resolve({ code: err ? (err.code ?? 1) : 0, stdout: stdout ?? "", stderr: stderr ?? "" });
    });
  });
}

// ── per-root serialization (review M2: one index.lock per shadow repo) ────────────────────────────
// In-process only: two dev servers on the same repo can still collide on index.lock — git fails that commit,
// run() surfaces non-zero, and commitRoot throws (logged, not corrupting). A cross-process file lock is later.
const locks = new Map();
function withLock(key, fn) {
  const prev = locks.get(key) ?? Promise.resolve();
  const next = prev.then(fn, fn); // run fn regardless of how the previous settled
  locks.set(
    key,
    next.then(
      () => {},
      () => {},
    ),
  );
  return next;
}

async function provision(gitDir, workTree) {
  if (fs.existsSync(path.join(gitDir, "HEAD"))) return; // idempotent
  fs.mkdirSync(gitDir, { recursive: true });
  const base = ["--git-dir", gitDir, "--work-tree", workTree];
  const init = await run([...base, "init", "--quiet"], workTree);
  if (init.code !== 0) throw new Error(`shadow git init failed: ${init.stderr.trim()}`);
  await run([...base, "config", "core.bare", "false"], workTree);
  await run([...base, "config", "user.name", "foolscap-canvas"], workTree);
  await run([...base, "config", "user.email", "canvas@foolscap.local"], workTree);
  await run([...base, "config", "commit.gpgSign", "false"], workTree);
  fs.writeFileSync(path.join(gitDir, "info", "exclude"), SHADOW_EXCLUDES);
}

// Commit `workTree` into its shadow ledger. Returns {committed:false} when nothing changed (no empty
// commits), else {committed:true, sha}. Serialized per shadow repo. Two staging modes:
//   • `paths` (attributed per-tool-call): stage ONLY those paths (`add --force -- <paths>`). Disjoint
//     staging is what keeps concurrent per-session commits truthful — each commit holds just its own file
//     — and `--force` lets an artefact edit under the ignored `.canvas/` track too.
//   • else (the `external` floor): `add -A` + force the artefacts dir, then unstage `exclude` paths so a
//     path a live tool_use has CLAIMED stays dirty for its own attributed commit (the watcher defer).
export function commitRoot(workTree, opts = {}) {
  const { rootId = "repo", gitRoot = workTree, message = "external edit", author = EXTERNAL_AUTHOR, paths, exclude } = opts;
  const gitDir = shadowGitDir(gitRoot, rootId);
  return withLock(gitDir, async () => {
    await provision(gitDir, workTree);
    const base = ["--git-dir", gitDir, "--work-tree", workTree];
    if (paths && paths.length) {
      const add = await run([...base, "add", "--force", "--", ...paths], workTree);
      if (add.code !== 0) throw new Error(`shadow add (paths) failed: ${add.stderr.trim()}`);
    } else {
      const add = await run([...base, "add", "-A"], workTree);
      if (add.code !== 0) throw new Error(`shadow add failed: ${add.stderr.trim()}`);
      // `.canvas/` is the canvas's filesystem (docs/canvas-home.md): images, channel logs, file-backed card
      // bodies, artefacts — all human-gitignored. Force-add the whole tree so it gets shadow history (a
      // negation pattern can't re-include past an excluded parent — see SHADOW_EXCLUDES), EXCLUDING only the
      // shadow object stores under `.canvas/roots/`: self-tracking them is churn and the feedback-loop source.
      // The `:(exclude)` pathspec prunes roots from the add itself, so the object DB is never staged-then-reset
      // (verified: stages .canvas/images + .canvas/artefacts, nothing under .canvas/roots). One rule — new
      // content subdirs need no change here. (Generalises the old artefacts-only force-add, docs/canvas-home §4.)
      // Also exclude `.canvas/worktrees/` — agent worktrees there are nested git checkouts (gitlinks); a
      // force-add would try to stage one as a submodule and fail (`is in submodule`). They reach main via
      // merge-on-green, not this ledger, so the canonical floor must never stage them.
      if (fs.existsSync(path.join(workTree, ".canvas"))) {
        const f = await run(
          [...base, "add", "--force", "--", ".canvas", ":(exclude).canvas/roots", ":(exclude).canvas/worktrees"],
          workTree,
        );
        if (f.code !== 0) throw new Error(`shadow .canvas add failed: ${f.stderr.trim()}`);
      }
      // Defer: leave claimed paths uncommitted (still dirty in the work-tree) so their attributed
      // `commitClaimed` — not this floor — captures them. `reset` only unstages; the work-tree is untouched.
      if (exclude && exclude.length) {
        await run([...base, "reset", "-q", "--", ...exclude], workTree);
      }
    }
    const diff = await run([...base, "diff", "--cached", "--quiet"], workTree);
    if (diff.code === 0) return { committed: false }; // nothing staged
    const commit = await run([...base, "commit", "-m", message, "--author", author, "--quiet"], workTree);
    if (commit.code !== 0) throw new Error(`shadow commit failed: ${commit.stderr.trim()}`);
    const head = await run([...base, "rev-parse", "HEAD"], workTree);
    return { committed: true, sha: head.stdout.trim() };
  });
}

// Live half (doc §5): watch a root and commit on settle, coalescing a burst of edits into one `external`
// commit. The caller supplies `ignored` (the engine's isInternalPath predicate — MUST exclude `.canvas/roots`
// or a commit's own object writes re-fire the watcher → loop; `.canvas/` CONTENT is watched so it's versioned,
// docs/canvas-home.md §5). Boot-reconcile is the caller's job: call commitRoot once before watching.
//
// Attribution (doc §6): a live editor tool_use `claim`s its target path so the settle floor SKIPS it (the
// watcher defer); the matching tool_result then `commitClaimed`s just that path, attributed to the session.
// So an attributed edit is never also committed `external`, and a path-scoped commit can't sweep in a
// concurrent agent's files. Paths are relative to `workTree` (git pathspec).
export function watchRoot(workTree, opts = {}) {
  const {
    rootId = "repo",
    gitRoot = workTree,
    settleMs = 800,
    author = EXTERNAL_AUTHOR,
    message = "external: edit",
    ignored,
    onCommit,
    onError,
  } = opts;
  let timer = null;
  const claimed = new Set(); // paths a live tool_use owns; the floor excludes them, commitClaimed releases them
  const fire = () => {
    timer = null;
    commitRoot(workTree, { rootId, gitRoot, author, message, exclude: [...claimed] }).then(
      (r) => {
        if (r.committed && onCommit) onCommit(r);
      },
      (e) => {
        if (onError) onError(e);
      },
    );
  };
  const settle = () => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(fire, settleMs);
  };
  const watcher = watch(workTree, { ignoreInitial: true, ignored });
  for (const ev of ["add", "change", "unlink", "addDir", "unlinkDir"]) watcher.on(ev, settle);
  return {
    // A live editor tool_use claims its target path(s): the `external` floor will leave them dirty so the
    // upcoming attributed commitClaimed — not the floor — captures them. Released on commit (or abandon).
    claim(paths) {
      for (const p of paths) claimed.add(p);
    },
    release(paths) {
      for (const p of paths) claimed.delete(p);
    },
    // Commit ONLY these paths, attributed to a session (per-tool-call, doc §6). Disjoint staging keeps it
    // truthful under concurrent agents. Releases the claim regardless of outcome (a failed/no-op edit just
    // returns committed:false). Serialized with the floor via commitRoot's per-root lock.
    async commitClaimed(paths, over = {}) {
      try {
        const r = await commitRoot(workTree, {
          rootId,
          gitRoot,
          author: over.author ?? author,
          message: over.message ?? message,
          paths,
        });
        if (r.committed && onCommit) onCommit(r);
        return r;
      } finally {
        for (const p of paths) claimed.delete(p);
      }
    },
    async close() {
      if (timer) clearTimeout(timer);
      await watcher.close();
    },
  };
}

// Read helpers for callers/tests: the tracked paths and the commit count of a root's shadow ledger.
export async function shadowTrackedPaths(workTree, opts = {}) {
  const { rootId = "repo", gitRoot = workTree } = opts;
  const gitDir = shadowGitDir(gitRoot, rootId);
  const r = await run(["--git-dir", gitDir, "--work-tree", workTree, "ls-tree", "-r", "--name-only", "HEAD"], workTree);
  return r.code === 0 ? r.stdout.split("\n").filter(Boolean) : [];
}

export async function shadowCommitCount(workTree, opts = {}) {
  const { rootId = "repo", gitRoot = workTree } = opts;
  const gitDir = shadowGitDir(gitRoot, rootId);
  const r = await run(["--git-dir", gitDir, "--work-tree", workTree, "rev-list", "--count", "HEAD"], workTree);
  return r.code === 0 ? Number(r.stdout.trim()) : 0;
}
